### PR TITLE
Fix macos build

### LINKED ISSUE #14: Build on Macos is broken
The build scripts have been only properly tested on Linux. It turns out that `sed` behaves in a slightly different way when executed in Mac, probably because of differences between GNU & BSD flavours.

Blocks #1 .

### PR DESCRIPTION
**Pull request by castarco**
Fixes #14  , and other minor problems.

### CODE REVIEW

File: scripts/build_esm.sh [hunk 1]
```diff
@@ -1,18 +1,49 @@
...
+	else
+		# Fix map references inside source files
+		sed -Ei 's/\/\/# sourceMappingURL=(.+)\.js\.map/\/\/# sourceMappingURL=\1.mjs.map/g' "${i%.*}.mjs";
 
-	# Fix imports in ESM files (we first remove existing extensions)
-	sed -Ei 's/\s+from\s+"\.\/(.+)\.m?js";/ from ".\/\1";/g' "${ii%.*}.mjs";
-	sed -Ei 's/\s+from\s+"\.\/(.+)";/ from ".\/\1.mjs";/g' "${ii%.*}.mjs";
+		# Fix imports in ESM files (we first remove existing extensions)
+		sed -Ei 's/\s+from\s+'"'"'\.\/(.+)\.m?js'"'"';/ from '"'"'.\/\1'"'"';/g' "${i%.*}.mjs";
+		sed -Ei 's/\s+from\s+'"'"'\.\/(.+)'"'"';/ from '"'"'.\/\1.mjs'"'"';/g' "${i%.*}.mjs";
```
Comment (castarco) [inline scripts/build_esm.sh:33]: After enforcing ESLint rules, both the source code & the generated files use `'` instead of `"`..

This strange block that looks like `'"'"'` is basically a concatenation of:
- `'` : end previous string
- `"` : start new string
- `'` : string content
- `"`: finish string
- `'`: start new string

and the shell takes care of concatenating the 3 strings.

File: scripts/build_cjs.sh [hunk 2]
```diff
@@ -1,14 +1,40 @@
...
+# Process source files
+for i in $( ls ./dist/cjs/*.js ); do
+	# Rename source files
+	mv $i ${i%.*}.cjs;
 
 	# Fix map references inside source files
-	sed -Ei 's/\/\/# sourceMappingURL=(.+)\.js\.map/\/\/# sourceMappingURL=\1.cjs.map/g' "${ii%.*}.cjs";
-done
+	if [ "${SED_VARIANT}" = "BSD" ]; then
+		sed -E -i '' 's/\/\/#[[:space:]]sourceMappingURL=(.+)\.js\.map/\/\/# sourceMappingURL=\1.cjs.map/g' "${i%.*}.cjs";
```
Comment (castarco) [inline scripts/build_cjs.sh:22]: - In the BSD flavour of `sed`, the `-i` option must be accompanied by an extension for the backup files (as `-i` is used for in-place replacements; it tries to force a more secure approach than the GNU flavour). In any case, we don't really need a backup, as we can easily regenerate the original files.
- Another difference is that BSD sed does not accept `\s` escape sequences to denote spaces :( , so we have to rely on the more bulky `[:space:]` character class (and surround it by another pair of square brackets).

**Review by ShogunPanda — APPROVED** [review]
